// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkG_hhXlVeJBARFdtfTvNLbgzQbaLhIo',
    appId: '1:782176025406:web:f327df22fc7dc55b914a6f',
    messagingSenderId: '782176025406',
    projectId: 'rezervacni-system-maturi-e12ef',
    authDomain: 'rezervacni-system-maturi-e12ef.firebaseapp.com',
    storageBucket: 'rezervacni-system-maturi-e12ef.firebasestorage.app',
    measurementId: 'G-30Z9NPX5K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CSlUFw5ZLZttTHz2-UVXO9n9QxFn2Xo',
    appId: '1:352059326498:android:4834c41740566907f68a7b',
    messagingSenderId: '352059326498',
    projectId: 'rezervacni-system-maturita',
    storageBucket: 'rezervacni-system-maturita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATH2Ej6WgaEa4i4hM6xHi1V15MoewmrUQ',
    appId: '1:352059326498:ios:429f0f14b51f4ebcf68a7b',
    messagingSenderId: '352059326498',
    projectId: 'rezervacni-system-maturita',
    storageBucket: 'rezervacni-system-maturita.firebasestorage.app',
    iosBundleId: 'com.example.rezervacniSystemMaturita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATH2Ej6WgaEa4i4hM6xHi1V15MoewmrUQ',
    appId: '1:352059326498:ios:429f0f14b51f4ebcf68a7b',
    messagingSenderId: '352059326498',
    projectId: 'rezervacni-system-maturita',
    storageBucket: 'rezervacni-system-maturita.firebasestorage.app',
    iosBundleId: 'com.example.rezervacniSystemMaturita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqkG_hhXlVeJBARFdtfTvNLbgzQbaLhIo',
    appId: '1:782176025406:web:a10c687fbc4cb37f914a6f',
    messagingSenderId: '782176025406',
    projectId: 'rezervacni-system-maturi-e12ef',
    authDomain: 'rezervacni-system-maturi-e12ef.firebaseapp.com',
    storageBucket: 'rezervacni-system-maturi-e12ef.firebasestorage.app',
    measurementId: 'G-QPK1GCV01H',
  );

}